### ISSUE TITLE
WARNING No response received

### ISSUE THREAD

**Issue by ppietro** [tomslee/airbnb-data-collection#27] opened 2018-01-03 17:39 UTC
Hi,

I had fun with your work, but if I try to search for Lisbon, at the end I get the message:

INFO:root:No progress logged for survey 2
INFO    No progress logged for survey 2
INFO:root:Bounding box: [38.795854, -9.090571, 38.691399, -9.229836]
INFO    Bounding box: [38.795854, -9.090571, 38.691399, -9.229836]
INFO:root:======================================================================
INFO    ======================================================================
INFO:root:Survey 2, for Lisbon--Portugal
INFO    Survey 2, for Lisbon--Portugal
INFO:root:Searching by bounding box, max_zoom=6
INFO    Searching by bounding box, max_zoom=6
INFO:root:----------------------------------------------------------------------
INFO    ----------------------------------------------------------------------
INFO:root:Searching rectangle: Private room, guests = 1, prices in [0, 40], zoom factor = 0
INFO    Searching rectangle: Private room, guests = 1, prices in [0, 40], zoom factor = 0
**WARNING:root:No response received from request despite multiple attempts: {'sw_lng': '-9.229836', 'ne_lat': '38.795854', 'source': 'filter', 'ne_lng': '-9.090571', 'room_types[]': 'Private room', 'price_min': '0', 'search_by_map': 'True', 'sw_lat': '38.691399', 'price_max': '40', 'page': '1', 'guests': '1'}**
WARNING No response received from request despite multiple attempts: {'sw_lng': '-9.229836', 'ne_lat': '38.795854', 'source': 'filter', 'ne_lng': '-9.090571', 'room_types[]': 'Private room', 'price_min': '0', 'search_by_map': 'True', 'sw_lat': '38.691399', 'price_max': '40', 'page': '1', 'guests': '1'}

issue related to user agent? Or something wrong from my side?

Thank you,
Pietro

**Comment by tomslee** [comment] 2018-01-04 02:49
Hi Pietro. 
- Can you tell me if this is a one-time warning? Every now and again some request will not get a response but it makes little difference.
- If it is something that happens a lot, or prevents you collecting data, could you tell me if you are using the latest build? I did make a change (from going to http://airbnb.com to https://airbnb.com) which fixed a problem that looked like this.

**Comment by ppietro** [comment] 2018-01-04 07:30
Hi,

thank you for your kind reply.

I get the message everytime. I tried to execute the script for some minutes, but the message was always the same.

I used the last release, with https://

If it might help, I do not have any proxy.

Thanks,
Pietro

**Comment by tomslee** [comment] 2018-01-06 01:56
Hi Pietro: it looks like Airbnb has made changes to its site that break the script. I have been looking at it, and I'm not sure if I can get the same information from it now. I'll try to update this issue in the next couple of days...

**Comment by ppietro** [comment] 2018-01-06 09:08
Hi,

I think yuo're right. I made some debug tests and I got the same conclusion.

Thanks,
Pietro

**Comment by LauraKim** [comment] 2018-01-25 07:09
Hi,

Same problem here with sb

**Comment by tomslee** [comment] 2018-01-27 20:25
The "develop" branch now has a fix that I'm testing out. First signs are that searches with -sb now work again. If a few cities complete properly I'll merge the change to the master branch so it becomes the default.

**Comment by LauraKim** [comment] 2018-02-04 01:43
Confirmed to be working again for the 2 cities I always run the script against.
Thanks a lot for the hard work!

**Comment by tomslee** [comment] 2018-02-05 00:48
Thanks for confirming @LauraKim. I've merged the "develop" branch into master again. 

I had a couple of cities when I first made changes that seemed to be too low in counts, but this week everything seemed to fit nicely on trend from earlier results, so I'm moving the changes to master and I'll close the issue (for now!).

**Closed by tomslee** 2018-02-05 00:48 UTC
